---
meta:
  target_mem: 144
  extras: (( grab meta.custom-extras || 0 ))

jobs:
- name: big_ones
  instances: (( calc "floor(meta.target_mem / 32)" ))

- name: small_ones
  instances: (( calc "floor((meta.target_mem - jobs.big_ones.instances * 32) / 16)" ))

- name: extra_ones
  instances: (( calc "2 + meta.extras" ))
