#!/usr/bin/perl

my $example = "";
my $inyaml = 0;

sub cat {
	my ($file, $line) = @_;
	my @l = ("```yml\n$line\n");
	open my $fh, "<", $file or die "failed to open $file: $!\n";
	push @l, $_ while <$fh>;
	close $fh;
	return @l;
}

die "USAGE: $0 ./README.md\n" unless @ARGV == 1;
open my $README, "<", $ARGV[0]
	or die "$ARGV[0]: $!\n";

my (@OUT, @YAML, @OVERRIDE);
while (<$README>) {
	chomp;
	$example = $1 if m/<a name="ex-(.*)"/;

	$inyaml = 1 if $_ eq "```yml";
	if ($_ eq "```") {
		$inyaml = 0;
		@OUT = (@OUT, @OVERRIDE > 0 ? @OVERRIDE : @YAML);
		@YAML = @OVERRIDE = ();
	}
	@OVERRIDE = cat($1, "# $1")
		if $inyaml and m|^# (examples/.*)\s*$|;
	@OVERRIDE = cat("examples/$example/output.yml", $_)
		if $inyaml and m|^\$ spruce merge|;

	if ($inyaml) {
		push @YAML, "$_\n";
		next;
	}
	push @OUT, "$_\n";
}
close $README;

open $README, ">", $ARGV[0]
	or die "$ARGV[0]: $!\n";
print $README $_ for @OUT;
close $README;
