on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - goos: linux
        - goos: windows
        - goos: darwin

    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: amd64
        binary_name: spruce-${{ matrix.goos }}-amd64
        build_flags:  '-ldflags="-X main.Version=${{ github.event.release.tag_name }}"'
    - name: validate binary version
      run: ./spruce-${{ matrix.goos }}-amd64 -v
