on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go list ./... | grep -v vendor | xargs go test

      - name: Vet
        run: go list ./... | grep -v vendor | xargs go vet

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: latest
          install-go: false

      - name: gosec
        run: go tool gosec ./...

      - name: CLI Tests
        run: |
          go build ./cmd/spruce
          ./assets/cli_tests
