on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build
